### ISSUE TITLE
RuntimeError: The size of tensor a (196) must match the size of tensor b (3136) at non-singleton dimension 2

### ISSUE THREAD

**Issue by HKLCXQ** [DaiShiResearch/TransNeXt#8]
Found a problem.
The code says something like this:
q_norm_scaled = (q_norm + self.query_embedding) * F.softplus(self.temperature) * self.seq_length_scale
But this x and q dimensions are both [1,196,64] and your input_resolution = img_size // (2 ** (i + 2), the first input_resolution = 56, 56 * 56 = 3196 doesn't match with 196 dimensions.

**Comment by JuergenZhang** [comment]
hello，我也遇到了这个问题，请问你是怎么解决的
